name: Lint

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'go.mod'
      - '**.go'
  pull_request:
    paths:
      - 'go.mod'
      - '**.go'

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Golang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m